### ISSUE TITLE
Why is go-zeromq/zmq4 not needing libzmq on windows?

### ISSUE THREAD

**Issue by willmendil** [go-zeromq/zmq4#130]
I tried using pebbe/zmq on windows (had great success of linux) but impossible to make it run as libzmq is need straight forward installable on windows. 
How come go-zeromq works no problem without these issues?

in other words, how would i modify pebbe to work as go-zeromq does since the latter is not going to be maintained?

**Comment by sbinet** [comment]
questions about installing [pebbe/zmq4](https://github.com/pebbe/zmq4) on Windows should be directed to the `pebbe/zmq4` project.

`go-zeromq/zmq4` is a pure-Go implementation of `0MQ`, from "first principles".
therefore, it doesn't need any C/C++ library to operate.
(the tests do ensure some amount of compatibility with the C/C++ libraries, through the use of `github.com/go-zeromq/goczmq`)
