### ISSUE TITLE
The connReaper goroutine may leak

### ISSUE THREAD

**Issue by egorse** [go-zeromq/zmq4#153]
It seems the socket.Close() only does sck.reaperCond.Signal() to close connReaper goroutine. But the signal seems can be delivered only if the connReaper is in sck.reaperCond.Wait().

That cause at least short leaving sockets (.Dial() and .Close()) sometimes to leak.

**Comment by egorse** [comment]
@sbinet would you mind to tag?

**Comment by sbinet** [comment]
done.
