### ISSUE TITLE
Send blocks on PUB

### ISSUE THREAD

**Issue by lunfardo314** [go-zeromq/zmq4#33]
1. The following code blocks on `Send` if there're no subscribers. I think it should never block on PUB socket.
 ```
pub := zmq4.NewPub(context.Background())
err := pub.Listen("tcp://*:3000")
err = pub.Send(zmq4.NewMsg([]byte("MSG")))
```
2. Also, after disconnecting of one of many SUBs, on PUB side Send starts returning an error while data is sent correctly.
How to publish correctly data to unknown number of subscribers with go-zeromq? 
I can't find any pure Go alternative.

**Comment by sbinet** [comment]
thanks for the report, and apologies for the belated answer.

wrt 1), could you check whether https://github.com/go-zeromq/zmq4/pull/36 fixes it for you?

wrt 2), it would help if you could provide me with a minimal reproducer. (and open another issue for that specific problem.)

**Comment by lunfardo314** [comment]
I can’t provide code for that anymore, sorry. I moved to pure Go nanomsg due to these problems and didn’t work with zmq anymore. 
I looked into the code and it seems pool of subscribers is not managed correctly on pub side in situations when sub and/or pub goes down and up in the middle. Pub keeps reporting errors even if sub is up again
