### ISSUE TITLE
connection not properly closed

### ISSUE THREAD

**Issue by fangdingjun** [go-zeromq/zmq4#34]
In rep/req mode, the connection used by zmq4 not properly closed, 

they are all stay at CLOSE_WAIT,

 the closed connection should be TIME_WAIT

`netstat -nat | grep 1234`

> tcp        0      0 127.0.0.1:49232         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49230         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49224         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49236         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49228         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49226         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49240         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49238         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49222         127.0.0.1:1234          FIN_WAIT2
> tcp        0      0 127.0.0.1:49234         127.0.0.1:1234          FIN_WAIT2
> tcp6       0      0 :::1234                 :::*                    LISTEN
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49222         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49236         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49238         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49226         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49224         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49232         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49230         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49234         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49228         CLOSE_WAIT
> tcp6       0      0 127.0.0.1:1234          127.0.0.1:49240         CLOSE_WAIT

the following code can reproduce the issue

test code for server, golang

    package main

    import (
        "context"
        "github.com/go-zeromq/zmq4"
        "log"
    )

    func main() {
        sock := zmq4.NewRep(context.Background())
        if err := sock.Listen("tcp://*:1234"); err != nil {
            log.Fatal(err)
        }

        for {
            msg, err := sock.Recv()
            if err != nil {
                log.Println("recv", err)
                continue
            }

            log.Printf("recv: %s", msg.Frames[0])
            if err := sock.Send(zmq4.NewMsg(msg.Frames[0])); err != nil {
                log.Println("send", err)
            }
        }
    }

test code for client, python

    import zmq
    import threading
    import time

    def f():
        ctx = zmq.Context()
        c = ctx.socket(zmq.REQ)
        c.connect("tcp://127.0.0.1:1234")

        c.send("1234")
        print(c.recv())
        time.sleep(1)
        c.close()

    threads = []
    for i in range(10):
        t = threading.Thread(target=f)
        threads.append(t)
        t.start()

    for t in threads:
        t.join()

**Comment by sbinet** [comment]
@fangdingjun thanks for the report.
could you check whether #35 fixes the issue for you?
