### ISSUE TITLE
Could you please tell me how to solve this problem?

### ISSUE THREAD

**Issue by sujunbo** [go-zeromq/zmq4#48]
go get: github.com/go-zeromq/zmq4@v0.6.0 requires
        github.com/zeromq/goczmq/v4@v4.2.1: reading github.com/zeromq/goczmq/go.mod at revision v4.2.1: unknown revision v4.2.1

**Comment by sbinet** [comment]
this should be fixed with `v0.6.2`.

thanks for the report!

(feel free to reopen otherwise.)
