### ISSUE TITLE
Multipart messages and TCP packets

### ISSUE THREAD

**Issue by jflam** [go-zeromq/zmq4#52]
Hello - I'm new to zmq, but when inspecting packets using Wireshark over a loopback connection, I see that the multipart message is being sent out in separate TCP frames. On the same machine, libzmq sends a multipart message within a single frame with the correct delimiters & length octets between each part of the multipart message. But in zmq4, it appears that you're sending the flags and length within a single packet and then the message part followed by the next flag and length in a TCP packet followed by the next part and so on. 

Is this expected? I haven't dug far enough into the implementation yet, but was wondering if 1) this is known and 2) this is expected?

Thx!

**Comment by Inphi** [comment]
You're correct. zmq4 sends each message separately. I'm working in a set of patches to optimize sending and publishing so multipart transmit is on my list. However, I haven't settled on what an efficient _zero-copy_ mutli-part transmit API should look like.
But for now, it should be transparently done similar to the API for reading a `zmq4.Msg`, even though this means unnecessary copying of slices, to keep the API symmetric.
