### ISSUE TITLE
zmq4: implement proper REQ/REP semantics

### ISSUE THREAD

**Issue by gertjaap** [go-zeromq/zmq4#70]
I'm using the REP/REQ sockets in a single-server multi-client scenario. According to the ZMQ docs, this should work properly because the server will send back the reply to the client it received the request from.

In my case however, i'm seeing that subsequent connects to the REP socket by other REQ sockets results in replies message being sent to all REQ sockets, and it acting more like a publish.

Is this supposed to work?

**Comment by gertjaap** [comment]
I've modified the unit test for rep-req to add a second req, which illustrates what's going wrong:

https://github.com/gertjaap/zmq4/blob/issue-70/zmq4_reqrep_test.go

**Comment by sbinet** [comment]
you're right.
the semantics of the `REQ/REP` pattern are not correctly implemented.

one would need to implement a specific `rpool/wpool` pair to correctly implement that pattern.
see [msgio.go](https://github.com/go-zeromq/zmq4/blob/master/msgio.go) for ideas on how this is done for other communication patterns.

**Comment by Inphi** [comment]
@sbinet I'm working on this
