### ISSUE TITLE
support to modify dial retry times.

### ISSUE THREAD

**Issue by Cylkal** [go-zeromq/zmq4#81]
Could you consider to add a new field in socket like `retryTimes`,  to support modify retry times in [socket.go](https://github.com/go-zeromq/zmq4/blob/master/socket.go#L236) , rather than use 10 as default, like:
```go
func WithDialerRetryTime(retryTimes int) Option {
	return func(s *socket) {
		s.retryTimes = retryTimes
	}
}
```

**Comment by sbinet** [comment]
SGTM.
do you want to send a PR?

**Comment by Cylkal** [comment]
alright, may be I can use contex to limit retry time.
