### ISSUE TITLE
Close on ipc:// cause unix socket be removed

### ISSUE THREAD

**Issue by egorse** [go-zeromq/zmq4#82]
Close on ipc:// cause unix socket be removed.

I would believe that's not what is should do, otherway client reconnection wont work after 1st connection.

**Comment by sbinet** [comment]
you're right.
the rationale for doing like so was: "who creates, cleans up". but it shouldn't prevent the valid use case you describe.

do you want to send a PR?

**Comment by egorse** [comment]
once my concern is valid - I will make PR soon

**Comment by egorse** [comment]
@sbinet I noticed that the closing listening ipc:// cause unix pipe to be removed - at least on Linux. Then why the pipe was removed explicitly in the code prior closing listening socket? 
Was there some purpose I may be unaware of and break by removing that piece of code?
Or I am just overthinking it? :)

**Comment by egorse** [comment]
Shame on me :( 
The go mod took some earlier version - this is working properly - pipe removed only for listener
