### ISSUE TITLE
Unable to dial ipv6 addresses

### ISSUE THREAD

**Issue by egorse** [go-zeromq/zmq4#83]
The reassembly dial address from string "tcp://[aaa:bbb::ccc]:55555" not working properly and tries to dual  "aaa:bbb::ccc:55555" instead of "[aaa:bbb::ccc]:55555"

**Comment by aldas** [comment]
Guys could you release new version with this fix? 

It is hard to create integration tests with random port when you set address to "tcp://0.0.0.0:0" and your system gives random ipv6 address to you (ala "[::]:35471"). but before you can now connect to it you need to parse it to "understandable" format for library before you can connect to test server.

**Comment by sbinet** [comment]
done.
