### ISSUE TITLE
Dial timeout?

### ISSUE THREAD

**Issue by ckoehler** [go-zeromq/zmq4#85]
I don't think ZMQ connects should be timing out like you are doing. See http://api.zeromq.org/4-1:zmq-connect, the whole point is that pub/sub/bind/connect order doesn't matter. pebbe/zmq4 does not time out on connect/Dial.

**Comment by sbinet** [comment]
you're right.

**Comment by ckoehler** [comment]
May be as simple as removing the check and return at https://github.com/go-zeromq/zmq4/blob/59e906cdade6f29bc7fdffd6da98393f7053ddd9/socket.go#L236. The sleep is a good idea. No expert, though.

Also, thanks so much for doing this, it's saving me a lot of pain trying to build my app for other architectures. No CGO is a win!

**Comment by ckoehler** [comment]
This is a better reference: https://rfc.zeromq.org/spec/23/#socket-semantics

**Comment by guidog** [comment]
Hi!

At the moment the user facing .Dial is synchronous. This should be kept that way.

The spec talks about "reconnect", which in my view is something different from the initial connect.

I would opt for the following:

1. leave the initial connect synchronous to get some errors back (network unreachable, unknown host etc.)
2. implement a reconnect method used after there has been a successful first connection

While implementing 1. I'd like to add a context.Context to the .Dial methods or add a .DialContext method.


Cheers
  Guido

**Comment by thielepaul** [comment]
I think that the numbers of retries should be configurable, if the user sets it to infinite (could be -1 or so) then the behavior will be very similar to the libzmq implementation, while still being synchronous

**Comment by thielepaul** [comment]
> do you want to try your hand at a PR?

yes, I think I could. Not sure when I will have time for it, though

**Comment by joaomagfreitas** [comment]
hey @sbinet 
this issue should be closed

**Comment by sbinet** [comment]
Fixed by https://github.com/go-zeromq/zmq4/pull/126
